server:
  port: 9009

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/funky
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: b9b9b0d6-22fd-410b-af7b-790281cbc0bc
        credential:
          client-id: 92163758-d332-4c00-9674-500bad840dd4
          client-secret: HsS8Q~C_tbSkZwCh88W.p7SbTq0UMK3Ry.mXlbPn
        application-type: web_application
#        user-name-attribute: email

logging:
  level:
    root: info
    com.diva.funky: debug
  file:
    path: /logs/${spring.application.name}
    name: ${logging.file.path}/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}-%d{yyyy-MM-dd}-%i.log
      clean-history-on-start: false
      max-file-size: 64MB
      total-size-cap: 2GB
      max-history: 7